### ISSUE TITLE
About the time of opening image 

### ISSUE THREAD

**Issue by LiuDong777** [ajkxyz/jpeg4py#5]
Thanks for sharing, I found the following interesting things:
1. If i continue to open the image, the running time will gradually decrease to a certain degree; 2. When the coding sleep  for 20s after opening an image, the running time is the same as the first time, could you help me analyze this, can you find a way to keep the image reading at a relatively fast speed regardless of the time interval?

**Comment by ajkxyz** [comment]
Looks like python garbage collection or some other factors on your PC like CPU thermal throttling as I've benchmarked it on my PC ensuring no thermal throttling, scaling governor set to performance and observed no noticeable deviation with or without garbage collection or with or without reusing resulting numpy array both with python2.7 and python3.6.

```python
#!/usr/bin/env python3
from __future__ import division, print_function

import gc
import jpeg4py as jpeg
import numpy as np
import time


def bench(name, reuse):
    x = None
    tt = []
    for i in range(500):
        t0 = time.time()
        if reuse and x is not None:
            jpeg.JPEG("test.jpg").decode(x)
        else:
            x = jpeg.JPEG("test.jpg").decode()
        dt = (time.time() - t0) * 1000.0
        tt.append(dt)
    if x is None:  # to prevent possibility of early garbage collection of x
        print("This should not happen")
    print("%s: min=%.3f max=%.3f mean=%.3f std=%.3f median=%.3f" %
          (name, np.min(tt), np.max(tt), np.mean(tt), np.std(tt), np.median(tt)))
    return tt


def main():
    # Heat up
    x = jpeg.JPEG("test.jpg").decode()
    del x
    gc.collect()

    # Benchmark
    tt_simple = bench("Simple", False)
    gc.collect()
    tt_reuse = bench("Reuse", True)
    gc.disable()
    gc.collect()
    tt_nogc = bench("No GC", False)
    gc.collect()
    tt_reuse_nogc = bench("Reuse No GC", True)
    gc.collect()
    gc.enable()

    import matplotlib.pyplot as plt
    plt.plot(tt_simple, "b-")
    plt.plot(tt_reuse, "b:")
    plt.plot(tt_nogc, "k-")
    plt.plot(tt_reuse_nogc, "k:")
    plt.show()


if __name__ == "__main__":
    main()
```
run with `sudo taskset -c 0 nice -n -5 python3 test.py`.

Example output python3.6:
```
Simple: min=53.822 max=57.110 mean=54.615 std=0.602 median=54.549
Reuse: min=53.762 max=56.853 mean=54.489 std=0.494 median=54.477
No GC: min=54.248 max=56.959 mean=55.009 std=0.512 median=54.991
Reuse No GC: min=53.751 max=56.986 mean=54.467 std=0.512 median=54.444
```
For python2.7:
```
Simple: min=53.061 max=56.235 mean=54.638 std=0.456 median=54.670
Reuse: min=53.538 max=55.801 mean=54.279 std=0.494 median=54.261
No GC: min=53.046 max=56.741 mean=54.846 std=0.519 median=54.847
Reuse No GC: min=53.521 max=55.967 mean=54.227 std=0.472 median=54.204
```

**Comment by LiuDong777** [comment]
Thanks for your demonstration, but the results I tested on my pc is like this, the image size is 2000*1000, For python3.6:
Simple: min=118.321 max=160.158 mean=136.433 std=13.365 median=134.732
Reuse: min=63.287 max=130.380 mean=79.856 std=21.310 median=70.730
No GC: min=122.970 max=161.468 mean=142.489 std=10.123 median=141.618
Reuse No GC: min=63.620 max=123.524 mean=77.796 std=15.835 median=74.650

**Comment by ajkxyz** [comment]
To exclude influence of another processes, please replace `time.time()` with `time.clock_gettime(time.CLOCK_PROCESS_CPUTIME_ID)` in the above example, that will measure CPU-only time excluding i/o.

I could not reproduce execution time increase in my environments. Even on raspberry pi there is no much deviance in execution time (tested with python 3.6.9 and numpy 1.13.3, 1.15.1, 1.16.4, 1.18.0), so I suspect it is a problem specific to your environment like CPU thermal throttling or buggy numpy/python.
